vim.g.mapleader = " "

require("config.options")
require("plugins.colorscheme")
require("config.lsp")
require("config.autocommands")
require("config.diagnostics")
require("config.formatting")
require("config.keymaps")

require("plugins.snacks")
require("plugins.mini_icons")
require("plugins.treesitter")
require("plugins.oil_config")
require("plugins.telescope")
require("plugins.fidget")
require("plugins.whichkey")
require("plugins.gitsigns")
require("plugins.neotest")
require("plugins.persistence")
require("plugins.autopairs")
require("plugins.flash")
require("plugins.lualine")
require("plugins.quicker")
